theme: jekyll-theme-cayman
title: GDG Cloud Vancouver
description: Google Developers Group, Cloud Vancouver
github:
  meetup_url: https://meetup.com/gdgcloudvancouver
  twitter_url: https://twitter.com/gdgvancouver
  owner_name: GDG Cloud Vancouver
  google_analytics: UA-34512503-4
